server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:PhumlaniDev/infinity-tech-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.config: DEBUG