server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:PhumlaniDev/infinity-tech-config.git
          profile: default
          label: main
#          username: ${GIT_USERNAME}
#          password: ${GIT_PASSWORD}
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://keycloak:8080/realms/mac-app
#  redis:
#    host: redis
#    port: 6379
#    cloud:
#      gateway:
#        routes:
#          - id: auth-service
#            uri: http://auth-service:9000
#            predicates:
#              - Path=/api/auth/**
#            filters:
#              - name: RequestRateLimiter
#                args:
#                  redis-rate-limiter.replenishRate: 10
#                  redis-rate-limiter.burstCapacity: 20
#                  redis-rate-limiter.requestedTokens: 1
#
management:
  endpoints:
    web:
      exposure:
        include: "*"